version: '3.6'  
services:  
  nestor:
    build:
      context: ./wiki
    container_name: wikipod
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
  database:
    image: mongo
    container_name: wikipod
    environment:
      - MONGO_INITDB_DATABASE=wiki
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017:27017'
